// Generate a small synthetic export directory in Meta's HTML shape.
//
// The repo must never contain a real Instagram export — it is full of personal
// data. This produces an obviously-fake one with the same markup structure, so
// the parsers can be exercised without anyone's real ZIP.
//
//   node tools/make-fixture.mjs [outputDir]
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const out = process.argv[2] ?? 'fixtures/synthetic-export';

const GENERATED = '2026-07-31T12:01Z';
const RANGE = ['2025-07-31T11:57Z', '2026-07-31T11:57Z'];
const REC = 'pam _3-95 _2ph- _a6-g uiBoxWhite noborder';

const page = (title, body) => `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>body{font-family:sans-serif}</style><title>${title}</title></head>
<body><div class="_a705"><header><h1>${title}</h1>
<aside class="_aoaa">Generated by testuser on <time datetime="${GENERATED}">Friday, July 31, 2026</time>
<div>Contains data you requested from <time datetime="${RANGE[0]}">July 31, 2025</time>
to <time datetime="${RANGE[1]}">July 31, 2026</time></div></aside></header>
<main class="_a706" role="main">${body}</main></div></body></html>`;

const rec = (inner) => `<div class="${REC}">${inner}</div>`;
const cell = (label, value) => `<tr><td class="_a6_q">${label}</td><td class="_2piu _a6_r">${value}</td></tr>`;
const tbl = (rows) => `<table>${rows.join('')}</table>`;
const wrap = (inner) => rec(`<div class="_a6-p">${inner}</div>`);

// Deterministic pseudo-randomness — a fixture that changes between runs is
// useless for regression testing.
let seed = 42;
const rand = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
const pick = (list) => list[Math.floor(rand() * list.length)];

const stamp = (d) => {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const h = d.getHours();
  const h12 = h % 12 || 12;
  return `${months[d.getMonth()]} ${String(d.getDate()).padStart(2, '0')}, ${d.getFullYear()} ` +
    `${h12}:${String(d.getMinutes()).padStart(2, '0')} ${h < 12 ? 'am' : 'pm'}`;
};
const dayOffset = (n) => new Date(2026, 0, 1 + n, 8 + Math.floor(rand() * 12), Math.floor(rand() * 60));

const CREATORS = ['alpha_creator', 'beta_maker', 'gamma_films', 'delta_daily', 'epsilon_eats'];
const FOLLOWERS = ['first_follower', 'second_soul', 'third_wheel', 'fourth_wall', 'fifth_element'];
const FOLLOWING = [...FOLLOWERS.slice(0, 3), 'sixth_sense', 'seventh_seal', 'eighth_note'];

const files = new Map();

// The Instagram logo sits on every exported page under `files/`; the avatar is
// the one under `media/`. Both are present here so the parser has to tell them
// apart rather than taking whichever <img> it meets first.
files.set('personal_information/personal_information/personal_information.html', page('Personal information',
  '<img src="files/Instagram-Logo.png" height="28" alt="Instagram" />' +
  '<img src="media/other/00000000000000000.jpg" class="_a6_o _3-96" />' +
  rec(`<h2 class="_3-95 _2pim _a6-h _a6-i">User Information</h2><div class="_a6-p">${tbl([
    '<tr><td colspan="2" class="_2pin _a6_q">Email<div><div>fixture@example.invalid</div></div></td></tr>',
    '<tr><td colspan="2" class="_2pin _a6_q">Phone Number<div><div>+10000000000</div></div></td></tr>',
    '<tr><td colspan="2" class="_2pin _a6_q">Username<div><div>testuser</div></div></td></tr>',
    '<tr><td colspan="2" class="_2pin _a6_q">Name<div><div>Test User</div></div></td></tr>',
    '<tr><td colspan="2" class="_2pin _a6_q">Date of birth<div><div>1990-01-01</div></div></td></tr>',
    '<tr><td colspan="2" class="_2pin _a6_q">Private Account<div><div>True</div></div></td></tr>',
  ])}</div>`)));

files.set('security_and_login_information/login_and_profile_creation/signup_details.html', page('Signup details',
  wrap(tbl([
    cell('Username', 'Test User'),
    cell('IP Address', '203.0.113.7'),
    cell('Time', stamp(new Date(2015, 7, 23, 12, 56))),
    cell('Email', 'fixture@example.invalid'),
    cell('Device', 'fixture-device'),
  ]))));

files.set('connections/followers_and_following/followers_1.html', page('Followers',
  FOLLOWERS.map((u, i) => wrap(
    `<div><div><a href="https://www.instagram.com/${u}">${u}</a></div><div>${stamp(dayOffset(i * 37))}</div></div>`,
  )).join('')));

files.set('connections/followers_and_following/following.html', page('Following',
  FOLLOWING.map((u, i) => rec(
    `<h2 class="_3-95 _2pim _a6-h _a6-i">${u}</h2><div class="_a6-p"><div><div>` +
    `<a href="https://www.instagram.com/_u/${u}">https://www.instagram.com/_u/${u}</a></div>` +
    `<div>${stamp(dayOffset(i * 23))}</div></div></div>`,
  )).join('')));

// Own posts: metadata table plus a nested Media block, as Meta writes them.
files.set('your_instagram_activity/media/posts.html', page('Posts',
  [0, 1, 2].map((i) => rec(`<div class="_3-95 _a6-p">${rec(`<div class="_a6-p">${tbl([
    cell('Media', `<div><div>Fixture post ${i} #testing #fixture</div></div>`),
    cell('Draft', 'False'),
    cell('Published', 'True'),
    cell('Latitude', i === 0 ? '12.345678901234' : '0'),
    cell('Longitude', i === 0 ? '77.987654321098' : '0'),
    cell('Paid partnership', i === 2 ? 'True' : 'False'),
    cell('Is an advertisement', 'False'),
    cell('Caption', `Fixture post ${i} #testing #fixture`),
    cell('Update time', stamp(dayOffset(i * 60 + 5))),
  ])}</div>`)}<div>${stamp(dayOffset(i * 60))}</div></div>`)).join('')));

files.set('your_instagram_activity/media/stories.html', page('Stories',
  Array.from({ length: 12 }, (_, i) => rec(
    `<h2 class="_3-95 _2pim _a6-h _a6-i">Fixture story ${i}</h2><div class="_a6-p">` +
    `${tbl([cell('Source type', pick(['feed_reshare', 'camera', 'boomerang']))])}` +
    `<div>${stamp(dayOffset(i * 11))}</div></div>`,
  )).join('')));

files.set('your_instagram_activity/media/reels.html', page('Reels',
  [0, 1].map((i) => rec(
    `<h2 class="_3-95 _2pim _a6-h _a6-i">Fixture reel ${i}</h2><div class="_a6-p">` +
    `${tbl([cell('Latitude', '0'), cell('Longitude', '0')])}<div>${stamp(dayOffset(i * 90 + 20))}</div></div>`,
  )).join('')));

// Liked posts, with the nested Owner and Hashtags sections.
const ownerBlock = (u) => `<tr><td colspan="2" class="_a6_q"><div>${rec(
  `<h2 class="_3-95 _2pim _a6-h _a6-i">Owner</h2><div class="_a6-p">${rec(
    `<div class="_a6-p">${tbl([cell('Name', `${u} display`), cell('Username', u)])}</div>`,
  )}</div>`,
)}</div></td></tr>`;

const hashtagBlock = (tags) => `<tr><td colspan="2" class="_a6_q"><div>${rec(
  `<h2 class="_3-95 _2pim _a6-h _a6-i">Hashtags</h2><div class="_a6-p"><div>` +
  `<div class="_2ph_ _a6_q">Name</div><div>${tags.map((t) => `<div>${rec(`<div class="_a6-p">${t}</div>`)}</div>`).join('')}</div>` +
  `</div></div>`,
)}</div></td></tr>`;

const interactionRecord = (u, i, tags) => rec(`<div class="_3-95 _a6-p">${rec(
  `<div class="_a6-p">${tbl([
    `<tr><td colspan="2" class="_a6_q">URL<div><a href="https://www.instagram.com/reel/FIXTURE${i}/">https://www.instagram.com/reel/FIXTURE${i}/</a></div></td></tr>`,
    cell('Caption', `Fixture caption ${i}`),
    hashtagBlock(tags),
    ownerBlock(u),
  ])}</div>`,
)}<div>${stamp(dayOffset(i))}</div></div>`);

files.set('your_instagram_activity/likes/liked_posts.html', page('Liked posts',
  Array.from({ length: 40 }, (_, i) =>
    interactionRecord(pick(CREATORS), i, [pick(['viral', 'fyp', 'reels', 'comedy'])])).join('')));

// Outgoing story interactions, filed apart from likes by Instagram.
for (const [name, count] of [['polls', 6], ['quizzes', 3], ['emoji_sliders', 2], ['countdowns', 1]]) {
  files.set(`your_instagram_activity/story_interactions/${name}.html`, page(name,
    Array.from({ length: count }, (_, i) =>
      interactionRecord(pick(CREATORS), 3000 + i, [])).join('')));
}

files.set('your_instagram_activity/story_interactions/stories_viewed.html', page('Stories viewed',
  Array.from({ length: 120 }, (_, i) =>
    interactionRecord(pick(CREATORS), 1000 + i, [pick(['viral', 'travel', 'food'])])).join('')));

files.set('ads_information/ads_and_topics/videos_watched.html', page('Videos watched',
  Array.from({ length: 30 }, (_, i) =>
    interactionRecord(pick(CREATORS), 2000 + i, ['sponsored'])).join('')));

files.set('ads_information/ads_and_topics/ads_viewed.html', page('Ads viewed',
  Array.from({ length: 15 }, (_, i) => rec(`<div class="_3-95 _a6-p">${rec(
    `<div class="_a6-p">${tbl([cell('Caption', `Fixture ad ${i}`), ownerBlock(`brand_${i % 4}`)])}</div>`,
  )}<div>${stamp(dayOffset(i * 3))}</div></div>`)).join('')));

files.set('your_instagram_activity/comments/post_comments_1.html', page('Post comments',
  Array.from({ length: 18 }, (_, i) => wrap(tbl([
    cell('Comment', `Fixture comment ${i} 🙂`),
    cell('Media Owner', pick(CREATORS)),
    cell('Time', stamp(dayOffset(i * 7))),
  ]))).join('')));

files.set('ads_information/instagram_ads_and_businesses/advertisers_using_your_activity_or_information.html',
  page('Advertisers using your activity or information',
    rec(`<div class="_3-95 _a6-p">${tbl([
      `<tr><td colspan="2" class="_a6_q">Advertisers that have uploaded an audience list containing entries that were matched to your Instagram profile<div>` +
      Array.from({ length: 25 }, (_, i) => `<div>${rec(`<div class="_a6-p">Fixture Advertiser ${i}</div>`)}</div>`).join('') +
      '</div></td></tr>',
    ])}</div>`)));

files.set('your_instagram_activity/messages/inbox/testfriend_1/message_1.html', page('Test Friend',
  Array.from({ length: 20 }, (_, i) => rec(
    `<h2 class="_3-95 _2pim _a6-h _a6-i">${i % 3 === 0 ? 'Test User' : 'Test Friend'}</h2>` +
    `<div class="_a6-p"><div>Fixture message ${i}</div><div>${stamp(dayOffset(i * 2))}</div></div>`,
  )).join('')));

files.set('security_and_login_information/login_and_profile_creation/login_activity.html', page('Login activity',
  Array.from({ length: 6 }, (_, i) => rec(
    `<h2 class="_3-95 _2pim _a6-h _a6-i">2026-0${i + 1}-01T00:00:00+00:00</h2><div class="_a6-p">${tbl([
      cell('Cookie Name', '*************************XYZ'),
      cell('IP Address', `198.51.100.${i}`),
      cell('Time', stamp(dayOffset(i * 30))),
      cell('User Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/153.0'),
    ])}</div>`,
  )).join('')));

// Accounts Instagram suggested unprompted, and the ones the user rejected.
files.set('ads_information/ads_and_topics/suggested_profiles_viewed.html', page('Suggested profiles',
  Array.from({ length: 12 }, (_, i) => wrap(tbl([
    cell('Name', `Suggested ${i}`),
    cell('Username', `suggested_${i}`),
  ])) + `<div>${stamp(dayOffset(i * 2))}</div>`).join('')));

files.set("ads_information/ads_and_topics/profiles_you're_not_interested_in.html", page('Not interested',
  Array.from({ length: 3 }, (_, i) => wrap(tbl([
    cell('Username', `suggested_${i}`),
  ])) + `<div>${stamp(dayOffset(i * 5))}</div>`).join('')));

// Checkout keeps a name and email that appear nowhere else in the archive.
files.set('your_instagram_activity/shopping/checkout_payment_information.html', page('Checkout',
  wrap(tbl([
    cell('Region', 'Asia Pacific'),
    cell('Name', 'Test User'),
    cell('Email', 'checkout-fixture@example.invalid'),
  ]))));

files.set('preferences/settings/notification_preferences.html', page('Notification preferences',
  ['Likes', 'Comments', 'New followers', 'Live videos'].map((type, i) => wrap(tbl([
    cell('Channel', i % 2 ? 'Email' : 'Push notifications'),
    cell('Notification type', type),
    cell('Value', i % 3 ? 'Off' : 'On'),
  ]))).join('')));

files.set('security_and_login_information/login_and_profile_creation/logout_activity.html', page('Logouts',
  Array.from({ length: 3 }, (_, i) => wrap(tbl([
    cell('IP Address', `198.51.100.${i}`),
    cell('Time', stamp(new Date(2026, 0, 1 + i * 30, 9, 30))),
    cell('User Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/153.0'),
  ]))).join('')));

files.set('connections/contacts/synced_contacts.html', page('Synced contacts',
  Array.from({ length: 9 }, (_, i) => wrap(tbl([
    cell('First Name', `Contact${i}`),
    cell('Contact Information', `555010${String(i).padStart(4, '0')}`),
  ]))).join('')));

for (const [path, html] of files) {
  const full = join(out, path);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, html);
}

// A real 1x1 JPEG at the avatar path, so the one binary the tool pulls out of
// the archive is exercised rather than assumed. Everything else under media/
// stays absent — the point is that only this file is ever decompressed.
const AVATAR = 'media/other/00000000000000000.jpg';
const avatarFull = join(out, AVATAR);
await mkdir(dirname(avatarFull), { recursive: true });
await writeFile(avatarFull, Buffer.from(
  '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a' +
  'HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAA' +
  'AAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==',
  'base64',
));

console.log(`wrote ${files.size} synthetic files + 1 image to ${out}`);
console.log('All names, handles, numbers and coordinates are fabricated.');
